package com.handpay.coupon.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.handpay.coupon.entity.GetCardData;
import com.handpay.coupon.entity.StoreData;

import com.handpay.coupon.dao.GetCardDataDao;
import com.handpay.coupon.dao.StoreDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig getCardDataDaoConfig;
    private final DaoConfig storeDataDaoConfig;

    private final GetCardDataDao getCardDataDao;
    private final StoreDataDao storeDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        getCardDataDaoConfig = daoConfigMap.get(GetCardDataDao.class).clone();
        getCardDataDaoConfig.initIdentityScope(type);

        storeDataDaoConfig = daoConfigMap.get(StoreDataDao.class).clone();
        storeDataDaoConfig.initIdentityScope(type);

        getCardDataDao = new GetCardDataDao(getCardDataDaoConfig, this);
        storeDataDao = new StoreDataDao(storeDataDaoConfig, this);

        registerDao(GetCardData.class, getCardDataDao);
        registerDao(StoreData.class, storeDataDao);
    }
    
    public void clear() {
        getCardDataDaoConfig.clearIdentityScope();
        storeDataDaoConfig.clearIdentityScope();
    }

    public GetCardDataDao getGetCardDataDao() {
        return getCardDataDao;
    }

    public StoreDataDao getStoreDataDao() {
        return storeDataDao;
    }

}
